# netlify.toml im Stammverzeichnis Ihres PORTFOLIO-Projekts

[[redirects]]
  # Der Pfad auf Ihrer Hauptdomain, der "maskiert" werden soll
  from = "/orderOfTheChosen/*"

  # Die "echte" URL Ihres gehosteten Spiels bei Netlify
  to = "https://order-of-the-chosen.netlify.app//:splat"

  # Status 200 bedeutet "Rewrite" (URL bleibt gleich), nicht "Redirect" (URL ändert sich)
  status = 200

  # 'force = true' stellt sicher, dass diese Regel auch für existierende Dateien greift
  force = true